"""add security_events table

Revision ID: ee9499881f43
Revises: a3017d29dc4f
Create Date: 2026-09-16 20:38:03.302278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee9499881f43'
down_revision: Union[str, Sequence[str], None] = 'a3017d29dc4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('claimed_tenant_slug', sa.String(length=255), nullable=True),
    sa.Column('claimed_tenant_id', sa.String(length=255), nullable=True),
    sa.Column('claimed_user_identity', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_events_created_at', 'security_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_security_events_created_at', table_name='security_events')
    op.drop_table('security_events')
    # ### end Alembic commands ###
