"""
Schema for the 7 domain areas required by this milestone. No prior model
code existed anywhere in this project or the audited source repos to
migrate from (see db/base.py docstring) — this is a clean build against
the spec's field list, not a port.

Design choices stated explicitly, not left implicit:

- Every tenant-scoped table carries `tenant_id` directly as a column and
  foreign key, even where it's technically derivable by joining through
  `session_id` (e.g. ConversationTurn, ToolCall). This is deliberate
  denormalization: it's what lets every tenant-isolation query filter on
  `tenant_id` directly with a real index, rather than requiring a join
  through voice_sessions first just to enforce the security boundary.
  Cheap to write (`tenant_id` is available at insert time in every code
  path that would insert these rows), and it's the difference between
  "tenant isolation is one indexed WHERE clause" and "tenant isolation
  depends on remembering to join correctly every time."
- Tenant delete cascades to everything under it (users, sessions, turns,
  tool calls/results, audit logs) — appropriate for real tenant
  offboarding. User delete does NOT cascade-delete their conversation
  history/tool calls/audit entries — it sets `user_id` to NULL on those
  instead (ON DELETE SET NULL), preserving the operational record while
  removing the link to a deleted user identity.
- `ToolCall.call_id` is a unique string column correlating 1:1 with the
  `call_id` already generated by `app/tools/registry.py`'s `execute()` —
  this is the join point between the in-memory audit trail that already
  exists there and this persistent one. `registry.py` itself is NOT
  modified this session (out of scope per explicit instruction); wiring
  it to actually write these rows is future work, noted in
  STATUS_REPORT.md, not silently implied as done here.
- No literal "authentication-related identity data" was ported into
  `User`, because none exists yet in this project — `app/security/` is
  still an empty placeholder (confirmed before writing this file). 
  `external_id` is a placeholder for whatever the eventual auth layer's
  subject identifier turns out to be (a JWT `sub` claim, most likely,
  matching the pattern from an earlier project) — not wired to anything
  real yet.
"""
import enum
import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, Index, Integer, String, Text, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class TenantStatus(str, enum.Enum):
    active = "active"
    suspended = "suspended"


class UserStatus(str, enum.Enum):
    active = "active"
    disabled = "disabled"


class VoiceSessionStatus(str, enum.Enum):
    active = "active"
    closed = "closed"
    error = "error"


class TurnRole(str, enum.Enum):
    user = "user"
    assistant = "assistant"
    system = "system"
    tool = "tool"


class ToolCallStatus(str, enum.Enum):
    pending = "pending"
    succeeded = "succeeded"
    failed = "failed"
    timed_out = "timed_out"
    # Added for the tool-persistence milestone: distinguishes "the registry
    # rejected this before the handler ever ran" (unknown tool name, or
    # arguments that failed Pydantic validation) from `failed` ("the
    # handler ran and raised/returned an error"). Collapsing these into one
    # status would make it impossible to tell, from the audit trail alone,
    # whether a real operational system was ever touched for a given call
    # — that distinction is the whole point of an audit log.
    rejected = "rejected"


class Tenant(Base):
    __tablename__ = "tenants"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    slug: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[TenantStatus] = mapped_column(
        Enum(TenantStatus, name="tenant_status"), nullable=False, default=TenantStatus.active
    )
    config: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    users: Mapped[list["User"]] = relationship(back_populates="tenant", cascade="all, delete-orphan")
    voice_sessions: Mapped[list["VoiceSession"]] = relationship(back_populates="tenant", cascade="all, delete-orphan")


class User(Base):
    __tablename__ = "users"
    __table_args__ = (
        UniqueConstraint("tenant_id", "external_id", name="uq_users_tenant_external_id"),
        Index("ix_users_tenant_id", "tenant_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    external_id: Mapped[str] = mapped_column(String(255), nullable=False)
    display_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    status: Mapped[UserStatus] = mapped_column(
        Enum(UserStatus, name="user_status"), nullable=False, default=UserStatus.active
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    tenant: Mapped["Tenant"] = relationship(back_populates="users")


class VoiceSession(Base):
    __tablename__ = "voice_sessions"
    __table_args__ = (Index("ix_voice_sessions_tenant_id", "tenant_id"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    current_language: Mapped[str] = mapped_column(String(8), nullable=False, default="en-IN")
    # Comma-separated language history — same shape as the earlier gateway
    # project's proven VoiceSession.language_history design.
    language_history: Mapped[str] = mapped_column(Text, nullable=False, default="en-IN")
    status: Mapped[VoiceSessionStatus] = mapped_column(
        Enum(VoiceSessionStatus, name="voice_session_status"), nullable=False, default=VoiceSessionStatus.active
    )
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    tenant: Mapped["Tenant"] = relationship(back_populates="voice_sessions")
    turns: Mapped[list["ConversationTurn"]] = relationship(back_populates="session", cascade="all, delete-orphan")
    tool_calls: Mapped[list["ToolCall"]] = relationship(back_populates="session", cascade="all, delete-orphan")


class ConversationTurn(Base):
    __tablename__ = "conversation_turns"
    __table_args__ = (Index("ix_conversation_turns_tenant_session", "tenant_id", "session_id"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    session_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("voice_sessions.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    role: Mapped[TurnRole] = mapped_column(Enum(TurnRole, name="turn_role"), nullable=False)
    text: Mapped[str] = mapped_column(Text, nullable=False)
    language: Mapped[str | None] = mapped_column(String(8), nullable=True)
    # e.g. which Moss/Qdrant sources were queried for this turn, similarity
    # scores, provider used — mirrors ContextBundle.sources_queried/degraded
    # from orchestrator.py, not invented independently of it.
    retrieval_metadata: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    session: Mapped["VoiceSession"] = relationship(back_populates="turns")


class ToolCall(Base):
    __tablename__ = "tool_calls"
    __table_args__ = (Index("ix_tool_calls_tenant_session", "tenant_id", "session_id"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    session_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("voice_sessions.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    tool_name: Mapped[str] = mapped_column(String(128), nullable=False)
    arguments: Mapped[dict] = mapped_column(JSONB, nullable=False)  # validated args if executed; raw (redacted) args if rejected — see registry.py
    status: Mapped[ToolCallStatus] = mapped_column(
        Enum(ToolCallStatus, name="tool_call_status"), nullable=False, default=ToolCallStatus.pending
    )
    # Correlates with ToolRegistry.execute()'s call_id — see module docstring.
    # NOTE: this is a CORRELATION id, freshly generated per execute() call.
    # It is deliberately NOT an idempotency key: two identical logical
    # requests produce two different call_ids. See idempotency_key below.
    call_id: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    #: Deterministic key derived from (tenant, session, tool, the
    #: contract's declared idempotency_fields) — see
    #: app/tools/idempotency.py. NULL for tools that don't declare KEYED
    #: idempotency, so the unique constraint only binds rows that opted in
    #: (Postgres treats NULLs as distinct in a UNIQUE index). The unique
    #: constraint is what makes duplicate suppression race-safe: two
    #: concurrent identical requests cannot both insert.
    idempotency_key: Mapped[str | None] = mapped_column(String(128), unique=True, nullable=True)
    requested_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    session: Mapped["VoiceSession"] = relationship(back_populates="tool_calls")
    result: Mapped["ToolResult | None"] = relationship(
        back_populates="tool_call", uselist=False, cascade="all, delete-orphan"
    )


class ToolResult(Base):
    __tablename__ = "tool_results"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tool_call_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("tool_calls.id", ondelete="CASCADE"), unique=True, nullable=False
    )
    success: Mapped[bool] = mapped_column(Boolean, nullable=False)  # never true unless the tool actually succeeded
    output: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    duration_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    tool_call: Mapped["ToolCall"] = relationship(back_populates="result")


class AuditLog(Base):
    __tablename__ = "audit_logs"
    __table_args__ = (Index("ix_audit_logs_tenant_id_created_at", "tenant_id", "created_at"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    action: Mapped[str] = mapped_column(String(128), nullable=False)
    resource_type: Mapped[str] = mapped_column(String(64), nullable=False)
    resource_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    # Python attribute is `event_metadata` (not `metadata`, which collides
    # with SQLAlchemy's own Base.metadata); actual column name is
    # "metadata" per the spec's field name. Never put secrets or raw tool
    # arguments/credentials here — structured event context only (e.g.
    # {"tool_name": "create_ticket"}, not {"api_key": "..."}).
    event_metadata: Mapped[dict] = mapped_column("metadata", JSONB, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class SecurityEvent(Base):
    """Security events occurring BEFORE a tenant could be verified — see
    docs/adr/001-audit-tenant-id.md for the full decision record.

    Deliberately has NO `tenant_id` column and NO foreign key to
    `tenants`. That is the entire point: the invariant "no audit record
    may claim an unverified tenant" is enforced by the shape of this
    table, not by remembering to be careful. There is no field here in
    which an unverified tenant could be asserted.

    `claimed_tenant_slug`/`claimed_tenant_id` are nullable STRINGS, named
    "claimed" on purpose. They preserve what an unauthenticated party
    asserted (forensically useful — e.g. spotting someone probing for
    valid tenant slugs) while being structurally incapable of being
    mistaken for a verified relationship. Nothing joins on them.

    Unlike `audit_logs`, rows here are NOT cascade-deleted with a tenant,
    because they belong to no tenant. Retention policy for this table is
    NOT implemented — see STATUS_REPORT.md's limitations.
    """

    __tablename__ = "security_events"
    __table_args__ = (Index("ix_security_events_created_at", "created_at"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    action: Mapped[str] = mapped_column(String(128), nullable=False)
    reason: Mapped[str] = mapped_column(String(128), nullable=False)  # e.g. "TenantNotFoundError"
    # What the unauthenticated party CLAIMED. Strings, not FKs. May be
    # entirely bogus — that is expected and is why they are recorded.
    claimed_tenant_slug: Mapped[str | None] = mapped_column(String(255), nullable=True)
    claimed_tenant_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    claimed_user_identity: Mapped[str | None] = mapped_column(String(255), nullable=True)
    resource_type: Mapped[str] = mapped_column(String(64), nullable=False)
    resource_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    # Never store credentials, tokens, or signatures here — only
    # non-sensitive structured context about the rejection.
    event_metadata: Mapped[dict] = mapped_column("metadata", JSONB, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
